### PR TITLE
Elements: Medication Search needs wider layout

### LINKED ISSUE #152: Elements: Advanced Medication Search Illegible
image

### PR DESCRIPTION
**Pull request by captDaylight**
Screen Shot 2023-03-29 at 12 22 12 PM

Screen Shot 2023-03-29 at 12 23 32 PM

closes #152

### CODE REVIEW

**Comment by jknapp25** [comment]
@captDaylight nice! On mobile, do you think this is still enough space to not have to wrap the dropdown option text?

**Comment by captDaylight** [comment]
@jknapp25 not sure I follow, nothing technically should be changed on mobile

here it is as it exists on my phone

IMG_CC3D090B771E-1

**Comment by jknapp25** [comment]
(Future idea) we could probably eek out a bit more space in a couple places...

Screen Shot 2023-03-29 at 9 35 05 AM

Chakra...

image

**Comment by captDaylight** [comment]
Screen Shot 2023-03-29 at 12 38 46 PM

**Comment by captDaylight** [comment]
ya makes sense, lemme just do the margin stuff now

**Review by jknapp25 — APPROVED** [review]

**Pull request merged**
